apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
